<?php

namespace App\Http\Controllers;

use App\Models\Factore;
use App\Models\Padrone;
use Illuminate\Http\Request;

class FactoreController extends Controller
{
    public function index($id){
        $padron=Padrone::find($id);
        $factores=Factore::where('padron_id','=',$id)->first();
        return view('factores.index',compact('padron','factores'));

    }
    public function store(Request $request){
        $factor=new Factore();
        $factor->padron_id=$request->id;
        if($request->hta==null){
            $factor->hta=0;
        }else{
            $factor->hta=1;
        }
        if($request->dbt==null){
            $factor->dbt=0;
        }else{
            $factor->dbt=1;
        }
        if($request->ob==null){
            $factor->ob=0;
        }else{
            $factor->ob=1;
        }
        if($request->sbp==null){
            $factor->sbp=0;
        }else{
            $factor->sbp=1;
        }
        if($request->tbq==null){
            $factor->tbq=0;
        }else{
            $factor->tbq=1;
        }
        if($request->emb==null){
            $factor->emb=0;
        }else{
            $factor->emb=1;
        }
        if($request->cns==null){
            $factor->cns=0;
        }else{
            $factor->cns=1;
        }
        if($request->dlp==null){
            $factor->dlp=0;
        }else{
            $factor->dlp=1;
        }
        if($request->rcv1==null){
            $factor->rcv1=0;
        }else{
            $factor->rcv1=1;
        }
        if($request->rcv2==null){
            $factor->rcv2=0;
        }else{
            $factor->rcv2=1;
        }
        if($request->rcv3==null){
            $factor->rcv3=0;
        }else{
            $factor->rcv3=1;
        }
        if($request->rcv4==null){
            $factor->rcv4=0;
        }else{
            $factor->rcv4=1;
        }
        if($request->rcv5==null){
            $factor->rcv5=0;
        }else{
            $factor->rcv5=1;
        }
        if($request->asma==null){
            $factor->asma=0;
        }else{
            $factor->asma=1;
        }
        if($request->alergia==null){
            $factor->alergia=0;
        }else{
            $factor->alergia=1;
        }
        if($request->anom==null){
            $factor->anom=0;
        }else{
            $factor->anom=1;
        }
        if($request->ear==null){
            $factor->ear=0;
        }else{
            $factor->ear=1;
        }
        if($request->pediatrico==null){
            $factor->pediatrico=0;
        }else{
            $factor->pediatrico=1;
        }
        if($request->vih==null){
            $factor->vih=0;
        }else{
            $factor->vih=1;
        }
        if($request->hipert==null){
            $factor->hipert=0;
        }else{
            $factor->hipert=1;
        }
        if($request->hipot==null){
            $factor->hipot=0;
        }else{
            $factor->hipot=1;
        }
        if($request->pps==null){
            $factor->pps=0;
        }else{
            $factor->pps=1;
        }
        $factor->save();

        return redirect()->route('hc.principal', $request->id);


    }
    public function update(Request $request){

        $factor=Factore::where('padron_id','=',$request->id)->first();
        if($request->hta==null){
            $factor->hta=0;
        }else{
            $factor->hta=1;
        }
        if($request->dbt==null){
            $factor->dbt=0;
        }else{
            $factor->dbt=1;
        }
        if($request->ob==null){
            $factor->ob=0;
        }else{
            $factor->ob=1;
        }
        if($request->sbp==null){
            $factor->sbp=0;
        }else{
            $factor->sbp=1;
        }
        if($request->tbq==null){
            $factor->tbq=0;
        }else{
            $factor->tbq=1;
        }
        if($request->emb==null){
            $factor->emb=0;
        }else{
            $factor->emb=1;
        }
        if($request->cns==null){
            $factor->cns=0;
        }else{
            $factor->cns=1;
        }
        if($request->dlp==null){
            $factor->dlp=0;
        }else{
            $factor->dlp=1;
        }
        if($request->rcv1==null){
            $factor->rcv1=0;
        }else{
            $factor->rcv1=1;
        }
        if($request->rcv2==null){
            $factor->rcv2=0;
        }else{
            $factor->rcv2=1;
        }
        if($request->rcv3==null){
            $factor->rcv3=0;
        }else{
            $factor->rcv3=1;
        }
        if($request->rcv4==null){
            $factor->rcv4=0;
        }else{
            $factor->rcv4=1;
        }
        if($request->rcv5==null){
            $factor->rcv5=0;
        }else{
            $factor->rcv5=1;
        }
        if($request->asma==null){
            $factor->asma=0;
        }else{
            $factor->asma=1;
        }
        if($request->alergia==null){
            $factor->alergia=0;
        }else{
            $factor->alergia=1;
        }
        if($request->anom==null){
            $factor->anom=0;
        }else{
            $factor->anom=1;
        }
        if($request->ear==null){
            $factor->ear=0;
        }else{
            $factor->ear=1;
        }
        if($request->pediatrico==null){
            $factor->pediatrico=0;
        }else{
            $factor->pediatrico=1;
        }
        if($request->vih==null){
            $factor->vih=0;
        }else{
            $factor->vih=1;
        }
        if($request->hipert==null){
            $factor->hipert=0;
        }else{
            $factor->hipert=1;
        }
        if($request->hipot==null){
            $factor->hipot=0;
        }else{
            $factor->hipot=1;
        }
        if($request->pps==null){
            $factor->pps=0;
        }else{
            $factor->pps=1;
        }
        $factor->save();

        return redirect()->route('hc.principal', $request->id);


    }
}
